#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_CLANKERS_CAVERN_ENTRANCE] = RandoRegion{ .regionName = "Clanker's Cavern Entrance", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_1,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_2,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_3,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_4,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_5,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_ENTRANCE_6,    CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_JIGGY_JINJO,            CAN_COLLECT_JINJOS(LEVEL_3_CLANKERS_CAVERN)),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE_UPPER,                   CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE_UNDERWATER,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CONNECTION(RR_GRUNTILDAS_LAIR_NEAR_ENTRANCE_CLANKERS_CAVERN,    true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_ENTRANCE_UPPER] = RandoRegion{ .regionName = "Upper Entrance", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_ENTRANCE_1,      CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_ENTRANCE_2,      CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_ENTRANCE_3,      CAN_ATTACK),
            CHECK(RC_CC_JINJO_YELLOW,                               CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_MUMBO_TOKEN_ABOVE_LEVEL_ENTRANCE,           CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_1,                 true),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_2,                 true),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_3,                 true),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_4,                 true),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_5,                 CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_6,                 CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_7,                 CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_8,                 CAN_EXTEND_JUMP_DISTANCE),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE,             CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE_UNDERWATER,  CAN_USE_ABILITY(ABILITY_F_DIVE)),
        },
    };

    Regions[RR_CLANKERS_CAVERN_ENTRANCE_UNDERWATER] = RandoRegion{ .regionName = "Entrance Underwater", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_1, true),
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_2, true),
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_3, true),
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_4, true),
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_5, true),
            CHECK(RC_CC_NOTE_ENTRANCE_TUNNEL_6, true),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE, true),
            CONNECTION(RR_CLANKERS_CAVERN_NEAR_CLANKER, true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_INTERIOR_CLANKER] = RandoRegion{ .regionName = "Inside Clanker", .mapId = MAP_22_CC_INSIDE_CLANKER,
        .checks = {
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_1,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_2,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_3,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_4,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_5,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_6,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_7,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_RINGS_8,              CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_SLOW_SAWBLADES_EXIT_1,     CAN_ACCESS_REGION(RR_CLANKERS_CAVERN_UNDERWATER_LOCK)),
            CHECK(RC_CC_BLUE_EGG_SLOW_SAWBLADES_EXIT_2,     CAN_ACCESS_REGION(RR_CLANKERS_CAVERN_UNDERWATER_LOCK)),
            CHECK(RC_CC_BLUE_EGG_SLOW_SAWBLADES_EXIT_3,     CAN_ACCESS_REGION(RR_CLANKERS_CAVERN_UNDERWATER_LOCK)),
            CHECK(RC_CC_BLUE_EGG_SLOW_SAWBLADES_EXIT_4,     CAN_ACCESS_REGION(RR_CLANKERS_CAVERN_UNDERWATER_LOCK)),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_INSIDE_CLANKER_1, CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_INSIDE_CLANKER_2, CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_INSIDE_CLANKER_3, CAN_ATTACK),
            CHECK(RC_CC_JIGGY_RINGS,                        CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_CC_JINJO_PINK,                         true),
            CHECK(RC_CC_JIGGY_TOOTH,                        true),
            CHECK(RC_CC_MUMBO_TOKEN_CLANKERS_LEFT_TOOTH,    true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_1,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_2,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_3,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_4,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_5,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_6,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_7,       true),
            CHECK(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_8,       true),
            CHECK(RC_CC_NOTE_LOWER_GILLS_TUNNEL_1,          true),
            CHECK(RC_CC_NOTE_LOWER_GILLS_TUNNEL_2,          true),
            CHECK(RC_CC_NOTE_LOWER_GILLS_TUNNEL_3,          true),
            CHECK(RC_CC_NOTE_LOWER_GILLS_TUNNEL_4,          true),
            CHECK(RC_CC_NOTE_LOWER_GILLS_TUNNEL_5,          true),
            CHECK(RC_CC_NOTE_NEAR_PINK_JINJO_1,             true),
            CHECK(RC_CC_NOTE_NEAR_PINK_JINJO_2,             true),
            CHECK(RC_CC_NOTE_NEAR_PINK_JINJO_3,             true),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_NEAR_CLANKER, true),
            CONNECTION(RR_CLANKERS_CAVERN_INTERIOR_CLANKER_FAST_SAWBLADE, CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
        },
    };

    Regions[RR_CLANKERS_CAVERN_INTERIOR_CLANKER_FAST_SAWBLADE] = RandoRegion{ .regionName = "Fast Sawblade Room", .mapId = MAP_23_CC_GOLDFEATHER_ROOM,
        .checks = {
            CHECK(RC_CC_JIGGY_FAST_SAWBLADES,   CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
            CHECK(RC_CC_MOLEHILL_WONDERWING,    true),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_1,  true),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_2,  true),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_3,  CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_4,  CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_5,  CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
            CHECK(RC_CC_NOTE_FAST_SAWBLADES_6,  CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_INTERIOR_CLANKER, true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_INTERIOR_CLANKER_SLOW_SAWBLADE] = RandoRegion{ .regionName = "Slow Sawblade Room", .mapId = MAP_21_CC_WITCH_SWITCH_ROOM,
        .checks = {
            CHECK(RC_CC_JIGGY_SLOW_SAWBLADES,   true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_1,  true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_2,  true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_3,  true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_4,  true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_5,  true),
            CHECK(RC_CC_NOTE_SLOW_SAWBLADES_6,  true),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_INTERIOR_CLANKER, true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_NEAR_CLANKER] = RandoRegion{ .regionName = "Near Clanker", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_1,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_2,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_3,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_4,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_5,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_6,               true),
            CHECK(RC_CC_BLUE_EGG_LEDGE_NEAR_CHOMPA_7,               true),
            CHECK(RC_CC_BLUE_EGG_NEAR_SNIPPETS_1,                   CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_SNIPPETS_2,                   CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_SNIPPETS_3,                   CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_SNIPPETS_4,                   CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_NEAR_SNIPPETS_5,                   CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_UNDERWATER_PIPE_1,                 CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_UNDERWATER_PIPE_2,                 CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_UNDERWATER_PIPE_3,                 CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_UNDERWATER_PIPE_4,                 CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_UNDERWATER_PIPE_5,                 CAN_USE_ABILITY(ABILITY_F_DIVE)),
            CHECK(RC_CC_BLUE_EGG_YELLOW_GRATE_1,                    CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_BLUE_EGG_YELLOW_GRATE_2,                    CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_EMPTY_HONEYCOMB_UNDERWATER,                 true),
            CHECK(RC_CC_EXTRA_LIFE_CLANKERS_LEFT_FIN,               true),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_YELLOW_GRATES_1, CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_YELLOW_GRATES_2, CAN_ATTACK),
            CHECK(RC_CC_HONEYCOMB_BEEHIVE_NEAR_THE_YELLOW_GRATES_3, CAN_ATTACK),
            CHECK(RC_CC_JIGGY_BOLT,                                 CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_CC_JIGGY_CLANKER_RAISED,                       true),
            CHECK(RC_CC_JIGGY_LONG_PIPE,                            true),
            CHECK(RC_CC_JIGGY_TAIL,                                 CAN_BREAK_OBJECT(RA_BREAK_OBJECT_GRATE) && CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_JIGGY_SNIPPETS,                             CAN_ATTACK && CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_JINJO_BLUE,                                 true),
            CHECK(RC_CC_MUMBO_TOKEN_CHOMPA_BEHIND_CLANKERS_TAIL,    true),
            CHECK(RC_CC_MUMBO_TOKEN_TUNNEL_RIGHT_OF_CLANKER,        true),
            CHECK(RC_CC_NOTE_ABOVE_BOLT_1,                          true),
            CHECK(RC_CC_NOTE_ABOVE_BOLT_2,                          true),
            CHECK(RC_CC_NOTE_ABOVE_BOLT_3,                          true),
            CHECK(RC_CC_NOTE_ABOVE_BOLT_4,                          true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_1,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_2,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_3,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_4,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_5,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_6,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_7,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_8,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_9,                           true),
            CHECK(RC_CC_NOTE_NEAR_TAIL_10,                          true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_1,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_2,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_3,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_4,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_5,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_6,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_7,                       true),
            CHECK(RC_CC_NOTE_NEAR_SNIPPETS_8,                       true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_1,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_2,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_3,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_4,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_5,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_6,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_7,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_8,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_9,                      true),
            CHECK(RC_CC_NOTE_TOP_OF_CLANKER_10,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_1,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_2,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_3,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_4,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_5,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_6,                     true),
            CHECK(RC_CC_NOTE_UNDERWATER_PIPE_7,                     true),
            CHECK(RC_CC_NOTE_YELLOW_GRATE_1,                        CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_NOTE_YELLOW_GRATE_2,                        true),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_ENTRANCE_UNDERWATER, true),
            CONNECTION(RR_CLANKERS_CAVERN_NEAR_CLANKER_UPPER, (CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP) || CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CONNECTION(RR_CLANKERS_CAVERN_INTERIOR_CLANKER_SLOW_SAWBLADE, true),
            CONNECTION(RR_CLANKERS_CAVERN_UNDERWATER_LOCK, true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_NEAR_CLANKER_UPPER] = RandoRegion{ .regionName = "Upper Area Near Clanker", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_BLUE_EGG_ABOVEWATER_PIPE_1,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_BLUE_EGG_ABOVEWATER_PIPE_2,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_BLUE_EGG_ABOVEWATER_PIPE_3,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_BLUE_EGG_ABOVEWATER_PIPE_4,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_BLUE_EGG_ABOVEWATER_PIPE_5,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_BLUE_EGG_ALCOVE_WITH_OPEN_GRATE_1,  CAN_ATTACK),
            CHECK(RC_CC_BLUE_EGG_ALCOVE_WITH_OPEN_GRATE_2,  CAN_ATTACK),
            CHECK(RC_CC_EMPTY_HONEYCOMB_ABOVEWATER,         CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_EXTRA_LIFE_YELLOW_GRATE,            CAN_EXTEND_JUMP_DISTANCE),
            CHECK(RC_CC_EXTRA_LIFE_JINJO_PIPE,              CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_JINJO_ORANGE,                       CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_CC_MUMBO_TOKEN_ALCOVE_WITH_OPEN_GRATE, CAN_ATTACK),
            CHECK(RC_CC_NOTE_CLIMBABLE_PIPE_1,              CAN_ATTACK),
            CHECK(RC_CC_NOTE_CLIMBABLE_PIPE_2,              CAN_ATTACK),
            CHECK(RC_CC_NOTE_CLIMBABLE_PIPE_3,              CAN_ATTACK),
            CHECK(RC_CC_NOTE_CLIMBABLE_PIPE_4,              CAN_ATTACK),
            CHECK(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_1,         CAN_ATTACK),
            CHECK(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_2,         CAN_ATTACK),
            CHECK(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_3,         CAN_ATTACK),
            CHECK(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_4,         CAN_ATTACK),
            CHECK(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_5,         CAN_ATTACK),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_NEAR_CLANKER, true),
        },
    };

    Regions[RR_CLANKERS_CAVERN_UNDERWATER_LOCK] = RandoRegion{ .regionName = "Near the Underwater Lock", .mapId = MAP_B_CC_CLANKERS_CAVERN,
        .checks = {
            CHECK(RC_CC_JINJO_GREEN,            true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_1, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_2, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_3, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_4, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_5, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_6, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_7, true),
            CHECK(RC_CC_NOTE_UNDERWATER_LOCK_8, true),
        },
        .connections = {
            CONNECTION(RR_CLANKERS_CAVERN_NEAR_CLANKER, true),
        },
    };

}, {});
// clang-format on