#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_MAD_MONSTER_MANSION_CHURCH_CLOCK_TOWER] = RandoRegion{ .regionName = "Church Clock Tower", .mapId = MAP_1B_MMM_MAD_MONSTER_MANSION,
        .checks = {
            CHECK(RC_MMM_JIGGY_CLOCKTOWER_TOP,      CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_CLOCKTOWER_ROOF_1,    true),
            CHECK(RC_MMM_NOTE_CLOCKTOWER_ROOF_2,    true),
            CHECK(RC_MMM_NOTE_CLOCKTOWER_ROOF_3,    true),
            CHECK(RC_MMM_NOTE_CLOCKTOWER_ROOF_4,    true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_EXTERIOR, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_CHURCH_EXTERIOR] = RandoRegion{ .regionName = "Church Exterior", .mapId = MAP_1B_MMM_MAD_MONSTER_MANSION,
        .checks = {
            CHECK(RC_MMM_JIGGY_CEMETARY_POTS,               CAN_USE_ABILITY(ABILITY_6_EGGS)),
            CHECK(RC_MMM_MUMBO_TOKEN_BEHIND_CHURCH,         true),
            CHECK(RC_MMM_MUMBO_TOKEN_ALCOVE_CLOCK_TOWER,    CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ABOVE_THE_ENTRANCE,    CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_1,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_2,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_3,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_4,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_5,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_6,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_7,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_8,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_MMM_NOTE_CHURCH_ROOFTOP_9,             CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE,                 CAN_BREAK_OBJECT(RA_BREAK_OBJECT_IRON_GATE)),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR,          CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_11_TURBO_TALON)),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_CLOCK_TOWER,       CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_WINDOW,   true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR] = RandoRegion{ .regionName = "Church Interior", .mapId = MAP_1C_MMM_CHURCH,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_NORTHEAST_1,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_NORTHEAST_2,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_NORTHWEST_1,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_NORTHWEST_2,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_SOUTHEAST_1,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_SOUTHEAST_2,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_SOUTHWEST_1,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_PEW_SOUTHWEST_2,           CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_LEFT_1,     CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_LEFT_2,     CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_LEFT_3,     CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_RIGHT_1,    CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_RIGHT_2,    CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_CHURCH_ORGAN_RIGHT_3,    CAN_ATTACK),
            CHECK(RC_MMM_MUMBO_TOKEN_TOP_OF_STOOL_INSIDE_CHURCH,    CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_ORGAN_PEDALS_1,                       true),
            CHECK(RC_MMM_NOTE_ORGAN_PEDALS_2,                       true),
            CHECK(RC_MMM_NOTE_CHURCH_PEW_NORTHEAST,                 CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_CHURCH_PEW_NORTHWEST,                 CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_CHURCH_PEW_SOUTHEAST,                 CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_CHURCH_PEW_SOUTHWEST,                 CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_EXTERIOR,              true),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_UPPER_ORGAN,  CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_UPPER_ORGAN] = RandoRegion{ .regionName = "Church Organ", .mapId = MAP_1C_MMM_CHURCH,
        .checks = {
            CHECK(RC_MMM_EXTRA_LIFE_CHURCH_PIPES,   true),
            CHECK(RC_MMM_JIGGY_MOTZAND,             CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CHECK(RC_MMM_NOTE_ORGAN_PIPES_1,        true),
            CHECK(RC_MMM_NOTE_ORGAN_PIPES_2,        true),
            CHECK(RC_MMM_NOTE_ORGAN_PIPES_3,        true),
            CHECK(RC_MMM_NOTE_ORGAN_PIPES_4,        true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR,          true),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_RAFTERS,  CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_RAFTERS] = RandoRegion{ .regionName = "Church Rafters", .mapId = MAP_1C_MMM_CHURCH,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_1,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_2,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_3,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_4,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_5,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_6,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_7,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_8,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_9,                 true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_10,                true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_11,                true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_RAFTERS_12,                true),
            CHECK(RC_MMM_EMPTY_HONEYCOMB_CHURCH_RAFTERS,            true),
            CHECK(RC_MMM_MUMBO_TOKEN_TOP_OF_RAFTER_INSIDE_CHURCH,   true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR,              true),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_UPPER_ORGAN,  true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_CHURCH_INTERIOR_WINDOW] = RandoRegion{ .regionName = "Church Banjo Kazooie Window", .mapId = MAP_2B_MMM_SECRET_CHURCH_ROOM,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_1,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_2,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_3,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_4,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_5,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_6,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_7,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_8,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_9,  true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_10, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_11, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_12, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_13, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_14, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_15, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_16, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_17, true),
            CHECK(RC_MMM_BLUE_EGG_CHURCH_WINDOW_18, true),
            CHECK(RC_MMM_EXTRA_LIFE_CHURCH_WINDOW,  true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_EXTERIOR, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_ENTRANCE] = RandoRegion{ .regionName = "Mad Monster Mansion", .mapId = MAP_1B_MMM_MAD_MONSTER_MANSION,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_MANSION_AWNING_1,                     CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_MANSION_AWNING_2,                     CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_MANSION_AWNING_3,                     CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_MANSION_AWNING_4,                     CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_MAZE_1,                               true),
            CHECK(RC_MMM_BLUE_EGG_MAZE_2,                               true),
            CHECK(RC_MMM_BLUE_EGG_MAZE_3,                               true),
            CHECK(RC_MMM_BLUE_EGG_NEAR_FOUNTAIN_1,                      true),
            CHECK(RC_MMM_BLUE_EGG_NEAR_FOUNTAIN_2,                      true),
            CHECK(RC_MMM_BLUE_EGG_NEAR_FOUNTAIN_3,                      true),
            CHECK(RC_MMM_BLUE_EGG_NEAR_FOUNTAIN_4,                      true),
            CHECK(RC_MMM_BLUE_EGG_NEAR_WELL_1,                          CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_BLUE_EGG_NEAR_WELL_2,                          CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_BLUE_EGG_NEAR_WELL_3,                          CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_BLUE_EGG_NEAR_WELL_4,                          CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_MAZE_1,               CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_MAZE_2,               CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_MAZE_3,               CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_TALL_GRASS_1,         CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_TALL_GRASS_2,         CAN_ATTACK),
            CHECK(RC_MMM_HONEYCOMB_BEEHIVE_IN_THE_TALL_GRASS_3,         CAN_ATTACK),
            CHECK(RC_MMM_JIGGY_JINJO,                           	    CAN_COLLECT_JINJOS(LEVEL_A_MAD_MONSTER_MANSION)),
            CHECK(RC_MMM_JINJO_BLUE,                                  	CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_JINJO_GREEN,                                 	CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_JINJO_ORANGE,                                	true),
            CHECK(RC_MMM_MUMBO_TOKEN_HIDDEN_NEAR_FOUNTAIN,            	true),
            CHECK(RC_MMM_MUMBO_TOKEN_IN_THE_MAZE,                     	true),
            CHECK(RC_MMM_MUMBO_TOKEN_INSIDE_WHIPCRACK_IN_FOUNTAIN,    	CAN_USE_ABILITY(ABILITY_6_EGGS)),
            CHECK(RC_MMM_MUMBO_TOKEN_NEAR_FRONT_TUMBLARS_SHED,        	true),
            CHECK(RC_MMM_MUMBO_TOKEN_NEXT_TO_MAZE_HEDGE_RAMP,         	CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_MUMBO_TOKEN_TOP_OF_TUMBLARS_SHED,            	CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_AROUND_THE_WELL_EAST_1,	              	CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_NOTE_AROUND_THE_WELL_EAST_2,                 	CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_NOTE_AROUND_THE_WELL_WEST_1,                 	CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_NOTE_AROUND_THE_WELL_WEST_2,                 	CAN_USE_ABILITY(ABILITY_7_FEATHERY_FLAP)),
            CHECK(RC_MMM_NOTE_GRASS_BEHIND_THE_MANSION_1,             	true),
            CHECK(RC_MMM_NOTE_GRASS_BEHIND_THE_MANSION_2,             	true),
            CHECK(RC_MMM_NOTE_GRASS_BEHIND_THE_MANSION_3,             	true),
            CHECK(RC_MMM_NOTE_MAIN_ENTRANCE_1,                        	true),
            CHECK(RC_MMM_NOTE_MAIN_ENTRANCE_2,                        	true),
            CHECK(RC_MMM_NOTE_MAIN_ENTRANCE_3,                        	true),
            CHECK(RC_MMM_NOTE_MAIN_ENTRANCE_4,                        	true),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_LOWER_NORTHEAST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_LOWER_NORTHWEST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_LOWER_SOUTHEAST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_LOWER_SOUTHWEST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_UPPER_NORTHEAST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_UPPER_NORTHWEST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_UPPER_SOUTHEAST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB)),
            CHECK(RC_MMM_NOTE_MANSION_EXTERIOR_UPPER_SOUTHWEST_CORNER,	CAN_USE_ABILITY(ABILITY_5_CLIMB)),
            CHECK(RC_MMM_NOTE_MAZE_1,                                 	true),
            CHECK(RC_MMM_NOTE_MAZE_2,                                 	true),
            CHECK(RC_MMM_NOTE_MAZE_3,                                 	true),
            CHECK(RC_MMM_NOTE_MAZE_4,                                 	true),
            CHECK(RC_MMM_NOTE_MAZE_5,                                 	true),
            CHECK(RC_MMM_NOTE_MAZE_6,                                 	true),
            CHECK(RC_MMM_NOTE_SHED_ROOF_1,                            	CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_SHED_ROOF_2,                            	CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_SHED_ROOF_3,                            	CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_SHED_ROOF_4,                            	CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_NOTE_STAGNANT_FOUNTAIN_1,                    	true),
            CHECK(RC_MMM_NOTE_STAGNANT_FOUNTAIN_2,                    	true),
            CHECK(RC_MMM_NOTE_STAGNANT_FOUNTAIN_3,                    	true),
            CHECK(RC_MMM_NOTE_STAGNANT_FOUNTAIN_4,                    	true),
        },
        .connections = {
            CONNECTION(RR_GRUNTILDAS_LAIR_NEAR_ENTRANCE_MAD_MONSTER_MANSION,    true),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_BARREL,                  CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_BATHROOM,                CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN))),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_BEDROOM,                 CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS) && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_CELLAR,                  CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WOODEN_DOOR)),
            CONNECTION(RR_MAD_MONSTER_MANSION_CHURCH_EXTERIOR,                  CAN_BREAK_OBJECT(RA_BREAK_OBJECT_IRON_GATE)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_DINING_ROOM,             CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WOODEN_DOOR) || (CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_MUMBOS_SKULL,            CAN_BREAK_OBJECT(RA_BREAK_OBJECT_IRON_GATE) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_TUMBLARS_SHED,           CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WOODEN_DOOR)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_WELL,                    true),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_BOTTOM_NORTH,     CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_BOTTOM_SOUTH,     CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS)),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_MIDDLE_WEST,      CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN))),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_TOP_ATTIC,        CAN_BREAK_OBJECT(RA_BREAK_OBJECT_WINDOWS) && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_BARREL] = RandoRegion{ .regionName = "Barrel at the House Front", .mapId = MAP_2F_MMM_WATERDRAIN_BARREL,
        .checks = {
            CHECK(RC_MMM_JIGGY_BARREL_INTERIOR,     true),
            CHECK(RC_MMM_NOTE_BARREL_INTERIOR_1,    true),
            CHECK(RC_MMM_NOTE_BARREL_INTERIOR_2,    true),
            CHECK(RC_MMM_NOTE_BARREL_INTERIOR_3,    true),
            CHECK(RC_MMM_NOTE_BARREL_INTERIOR_4,    true),
            CHECK(RC_MMM_NOTE_BARREL_INTERIOR_5,    true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_BATHROOM] = RandoRegion{ .regionName = "Bathroom", .mapId = MAP_2C_MMM_BATHROOM,
        .checks = {
            CHECK(RC_MMM_MUMBO_TOKEN_IN_LOGGOS_ROOM, true),
            CHECK(RC_MMM_SNS_GREEN_EGG,              true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_INSIDE_LOGGO, CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_BEDROOM] = RandoRegion{ .regionName = "Bedroom", .mapId = MAP_2D_MMM_BEDROOM,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_BEDROOM_1, true),
            CHECK(RC_MMM_BLUE_EGG_BEDROOM_2, true),
            CHECK(RC_MMM_BLUE_EGG_BEDROOM_3, true),
            CHECK(RC_MMM_JINJO_YELLOW,                  CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_MUMBO_TOKEN_INSIDE_BEDROOM,    true),
            CHECK(RC_MMM_NOTE_BEDROOM_1,                true),
            CHECK(RC_MMM_NOTE_BEDROOM_2,                true),
            CHECK(RC_MMM_NOTE_BEDROOM_3,                true),
            CHECK(RC_MMM_NOTE_BEDROOM_4,                true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_CELLAR] = RandoRegion{ .regionName = "Cellar", .mapId = MAP_1D_MMM_CELLAR,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_CELLAR_1,                     CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_BLUE_EGG_CELLAR_2,                     CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_BLUE_EGG_CELLAR_3,                     CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_JIGGY_CELLAR,                          CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_JINJO_PINK,                            CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_MUMBO_TOKEN_INSIDE_BARREL_IN_CELLAR,   CAN_BREAK_OBJECT(RA_BREAK_OBJECT_CELLAR_CASK)),
            CHECK(RC_MMM_NOTE_BASEMENT_1,                       CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_BASEMENT_2,                       CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_BASEMENT_3,                       CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_NOTE_BASEMENT_4,                       CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_MMM_SNS_CYAN_EGG,                          true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_DINING_ROOM] = RandoRegion{ .regionName = "Dining Room", .mapId = MAP_26_MMM_NAPPERS_ROOM,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_DINING_ROOM_MANTLE_1,             CAN_USE_ABILITY(ABILITY_9_FLIGHT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_BLUE_EGG_DINING_ROOM_MANTLE_2,             CAN_USE_ABILITY(ABILITY_9_FLIGHT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_BLUE_EGG_DINING_ROOM_MANTLE_3,             CAN_USE_ABILITY(ABILITY_9_FLIGHT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_BLUE_EGG_DINING_ROOM_MANTLE_4,             CAN_USE_ABILITY(ABILITY_9_FLIGHT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_BLUE_EGG_DINING_ROOM_MANTLE_5,             CAN_USE_ABILITY(ABILITY_9_FLIGHT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_EXTRA_LIFE_DINING_ROOM_CHANDELIER,         CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_MMM_JIGGY_MANSION_TABLE,                       CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_MMM_MUMBO_TOKEN_IN_CHIMNEY_INSIDE_DINING_ROOM, CAN_USE_ABILITY(ABILITY_12_WONDERWING)),
            CHECK(RC_MMM_NOTE_CHAIR_WEST_SIDE_1,                    true),
            CHECK(RC_MMM_NOTE_CHAIR_WEST_SIDE_2,                    true),
            CHECK(RC_MMM_NOTE_CHAIR_WEST_SIDE_3,                    true),
            CHECK(RC_MMM_NOTE_CHAIR_NORTH_SIDE_1,                   true),
            CHECK(RC_MMM_NOTE_CHAIR_NORTH_SIDE_2,                   true),
            CHECK(RC_MMM_NOTE_CHAIR_EAST_SIDE_1,                    true),
            CHECK(RC_MMM_NOTE_CHAIR_EAST_SIDE_2,                    true),
            CHECK(RC_MMM_NOTE_CHAIR_EAST_SIDE_3,                    true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_INSIDE_LOGGO] = RandoRegion{ .regionName = "Inside Loggo", .mapId = MAP_8D_MMM_INSIDE_LOGGO,
        .checks = {
            CHECK(RC_MMM_JIGGY_INSIDE_LOGGO,        true),
            CHECK(RC_MMM_MUMBO_TOKEN_INSIDE_LOGGO,  true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_INTERIOR_BATHROOM, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_MUMBOS_SKULL] = RandoRegion{ .regionName = "Inside Mumbos Skull", .mapId = MAP_30_MMM_MUMBOS_SKULL,
        .checks = {
            CHECK(RC_MMM_NOTE_MUMBOS_SKULL_INTERIOR_1, true),
            CHECK(RC_MMM_NOTE_MUMBOS_SKULL_INTERIOR_2, true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP))
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_TUMBLARS_SHED] = RandoRegion{ .regionName = "Inside Tumblar's Shed", .mapId = MAP_24_MMM_TUMBLARS_SHED,
        .checks = {
            CHECK(RC_MMM_JIGGY_TUMBLARS_PUZZLE, true),
            CHECK(RC_MMM_NOTE_SHED_INTERIOR_1,  true),
            CHECK(RC_MMM_NOTE_SHED_INTERIOR_2,  true),
            CHECK(RC_MMM_NOTE_SHED_INTERIOR_3,  true),
            CHECK(RC_MMM_NOTE_SHED_INTERIOR_4,  true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_WELL] = RandoRegion{ .regionName = "Inside the Well", .mapId = MAP_25_MMM_WELL,
        .checks = {
            CHECK(RC_MMM_JIGGY_INSIDE_THE_WELLS_BUCKET, CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_MUMBO_TOKEN_INSIDE_WELL,       CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_1,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_2,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_3,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_4,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_5,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_6,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_NOTE_WELL_INTERIOR_7,          CAN_USE_ABILITY(ABILITY_F_DIVE) || CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, CAN_USE_ABILITY(ABILITY_5_CLIMB) || GET_CURRENT_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_BOTTOM_NORTH] = RandoRegion{ .regionName = "Bottom North Window", .mapId = MAP_2A_MMM_FEATHER_ROOM,
        .checks = {
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_BOTTOM_SOUTH] = RandoRegion{ .regionName = "Bottom South Window", .mapId = MAP_28_MMM_EGG_ROOM,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_1, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_2, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_3, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_4, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_5, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_6, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_7, true),
            CHECK(RC_MMM_BLUE_EGG_EGG_ROOM_8, true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_MIDDLE_WEST] = RandoRegion{ .regionName = "Middle West Window", .mapId = MAP_2E_MMM_HONEYCOMB_ROOM,
        .checks = {
            CHECK(RC_MMM_BLUE_EGG_HONEYCOMB_ROOM_1,                 CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_HONEYCOMB_ROOM_2,                 CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_HONEYCOMB_ROOM_3,                 CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_HONEYCOMB_ROOM_4,                 CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_BLUE_EGG_HONEYCOMB_ROOM_5,                 CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
            CHECK(RC_MMM_EMPTY_HONEYCOMB_BENEATH_THE_FLOORBOARDS,   CAN_USE_TRANSFORMATION(TRANSFORM_3_PUMPKIN)),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

    Regions[RR_MAD_MONSTER_MANSION_INTERIOR_WINDOW_TOP_ATTIC] = RandoRegion{ .regionName = "Attic", .mapId = MAP_29_MMM_NOTE_ROOM,
        .checks = {
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_1, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_2, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_3, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_4, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_5, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_6, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_7, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_8, true),
            CHECK(RC_MMM_NOTE_FRONT_WINDOW_ATTIC_9, true),
        },
        .connections = {
            CONNECTION(RR_MAD_MONSTER_MANSION_ENTRANCE, true),
        },
    };

}, {});
// clang-format on