#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_RUSTY_BUCKET_BAY_ENTRANCE] = RandoRegion{ .regionName = "Rusty Bucket Bay", .mapId = MAP_31_RBB_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_BETWEEN_SHIPPING_CONTAINERS_1,			CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CHECK(RC_RBB_BLUE_EGG_BETWEEN_SHIPPING_CONTAINERS_2,			CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CHECK(RC_RBB_BLUE_EGG_BETWEEN_SHIPPING_CONTAINERS_3,			CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CHECK(RC_RBB_BLUE_EGG_BETWEEN_SHIPPING_CONTAINERS_4,			CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CHECK(RC_RBB_BLUE_EGG_ENTRANCE_1,								true),
			CHECK(RC_RBB_BLUE_EGG_ENTRANCE_2,								true),
			CHECK(RC_RBB_BLUE_EGG_ENTRANCE_3,								true),
			CHECK(RC_RBB_BLUE_EGG_ENTRANCE_4,								CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_ENTRANCE_5,								CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_1,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_2,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_3,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_4,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_5,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_NEAR_PINK_JINJO_6,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_ON_LIFE_BOAT_1,							true),
			CHECK(RC_RBB_BLUE_EGG_ON_LIFE_BOAT_2,							true),
			CHECK(RC_RBB_BLUE_EGG_ON_LIFE_BOAT_3,							true),
			CHECK(RC_RBB_BLUE_EGG_TOP_OF_SHIP_1,							true),
			CHECK(RC_RBB_BLUE_EGG_TOP_OF_SHIP_2,							true),
			CHECK(RC_RBB_BLUE_EGG_TOP_OF_SHIP_3,							true),
			CHECK(RC_RBB_BLUE_EGG_TOP_OF_SHIP_4,							true),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_GRATE_ABOVE_PINK_JINJO_1,		CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_GRATE_ABOVE_PINK_JINJO_2,		CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_GRATE_ABOVE_PINK_JINJO_3,		CAN_ATTACK),
			CHECK(RC_RBB_JIGGY_CRANE_CAGE, 									CAN_USE_ABILITY(ABILITY_0_BARGE) && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_JIGGY_FUNNEL, 										CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_JIGGY_JINJO, 										CAN_COLLECT_JINJOS(LEVEL_9_RUSTY_BUCKET_BAY)),
			CHECK(RC_RBB_JIGGY_PROPELLOR, 									CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST) && CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_SECOND) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_JIGGY_SNORKEL, 									CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_JIGGY_WHISTLE, 									CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP))),
			CHECK(RC_RBB_JINJO_GREEN, 										CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_JINJO_ORANGE, 										CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_JINJO_PINK, 										CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_JINJO_YELLOW, 										true),
			CHECK(RC_RBB_MUMBO_TOKEN_TOXIC_WASTE_POND, 						CAN_EXTEND_JUMP_DISTANCE && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || (CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)))),
			CHECK(RC_RBB_MUMBO_TOKEN_ON_LIFE_BOAT, 							true),
			CHECK(RC_RBB_MUMBO_TOKEN_SHIPS_PROW, 							true),
			CHECK(RC_RBB_MUMBO_TOKEN_UNDER_CHOMPA_IN_WITCH_SWITCH_TOWER,	CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_SHIPS_CHIMNEY, 					CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_MUMBO_TOKEN_FRONT_OF_CHOMPA_LEFT_OF_SHIP, 			CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_1, 					true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_2, 					true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_3, 					true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_4, 					true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_1, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_2, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_3, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_4, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_1, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_2, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_3, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_4, 			CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_1, 					(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_2, 					(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_3, 					(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_4, 					(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_5, 					(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_1, 					CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_2, 					CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_3, 					CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_4, 					CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_1, 							(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_2, 							(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_3, 							(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_1, 								true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_2, 								true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_3, 								true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_4, 								true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_5, 								true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_1, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_2, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_3, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_4, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_5, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_6, 									true),
			CHECK(RC_RBB_NOTE_SHIP_STERN_1, 								CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_SHIP_STERN_2, 								CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_1, 							CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_2, 							CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_3, 							CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_1, 					CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_2, 					CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_3, 					CAN_EXTEND_JUMP_DISTANCE),
		},
		.connections = {
			CONNECTION(RR_GRUNTILDAS_LAIR_NEAR_ENTRANCE_RUSTY_BUCKET_BAY,		true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ANCHOR,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BOAT_HOUSE,					CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BOSS_BOOM_BOX_ROOM,			CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_0_BARGE) && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BUNK_CABIN,					CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_CAPTAINS_CABIN,				CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_BEHIND_GLASS,	true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_MAIN,			CAN_ATTACK),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_KITCHEN,					true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_NAVIGATION_ROOM,			CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_FIRST,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_SECOND,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_THIRD,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_TNT_ROOM,					true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_LOWER,			true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_UPPER,			CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
		},
		.events = {
			EVENT(RA_WITCH_SWITCH_RUSTY_BUCKET_BAY, CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ANCHOR] = RandoRegion{ .regionName = "Anchor Interior", .mapId = MAP_8B_RBB_ANCHOR_ROOM,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_ANCHOR_ROOM_1,	CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_ANCHOR_ROOM_2,	CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_ANCHOR_ROOM_3,	CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_BLUE_EGG_ANCHOR_ROOM_4,	CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_1,		true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_2,		true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_3,		true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_4,		true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, CAN_USE_ABILITY(ABILITY_F_DIVE)),
		},
		.events = {
			EVENT(RA_TRIGGER_SWITCH_RBB_ANCHOR, CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BOAT_HOUSE] = RandoRegion{ .regionName = "Boat House", .mapId = MAP_36_RBB_BOATHOUSE,
        .checks = {
			CHECK(RC_RBB_EMPTY_HONEYCOMB_BOAT_HOUSE, CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, CAN_USE_ABILITY(ABILITY_F_DIVE)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BOSS_BOOM_BOX_ROOM] = RandoRegion{ .regionName = "Boom Box Room", .mapId = MAP_3A_RBB_BOSS_BOOM_BOX,
        .checks = {
			CHECK(RC_RBB_JIGGY_BOSS_BOOM_BOX, CAN_ATTACK),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BUNK_CABIN] = RandoRegion{ .regionName = "Bunk Cabin", .mapId = MAP_39_RBB_CREW_CABIN,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BUNK_IN_CABIN,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_1, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_2, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_3, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_4, 				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_CAPTAINS_CABIN] = RandoRegion{ .regionName = "Captains Cabin", .mapId = MAP_3F_RBB_CAPTAINS_CABIN,
        .checks = {
			CHECK(RC_RBB_JIGGY_CAPTAINS_CABIN, 	CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP) || CAN_USE_ABILITY(ABILITY_0_BARGE) || CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_1,	true),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_2,	true),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_3,	true),
			CHECK(RC_RBB_SNS_RED_EGG,			true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_BEHIND_GLASS] = RandoRegion{ .regionName = "Engine Room Behind Glass", .mapId = MAP_34_RBB_ENGINE_ROOM,
        .checks = {
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_1, true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_2, true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_3, true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_4, true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		},
		.events = {
			EVENT(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST, CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_MAIN] = RandoRegion{ .regionName = "Engine Room Main", .mapId = MAP_34_RBB_ENGINE_ROOM,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_ENGING_ROOM_1,					CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_BLUE_EGG_ENGING_ROOM_2,					CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_BLUE_EGG_ENGING_ROOM_3,					CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_BLUE_EGG_ENGING_ROOM_4,					CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_EXTRA_LIFE_ENGINE_ROOM, 					CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_EMPTY_HONEYCOMB_ENGINE_ROOM, 				CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_ENGINE_ROOM_ENTRANCE_1,	CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_ENGINE_ROOM_ENTRANCE_2,	CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_ENGINE_ROOM_ENTRANCE_3,	CAN_ATTACK),
			CHECK(RC_RBB_JIGGY_ENGINE_ROOM, 						CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_LEFT_PIPE, 		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_RIGHT_PIPE, 		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_SPINNING_PLATFORM,	true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_1, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_2, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_3, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_4, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_1, 				CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_2, 				CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_3, 				CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_4, 				CAN_ACCESS(RA_TRIGGER_SWITCH_RBB_PROPELLOR_FIRST)),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_1, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_2, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_3, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_4, 					true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		},
		.events = {
			EVENT(RA_TRIGGER_SWITCH_RBB_PROPELLOR_SECOND, CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_KITCHEN] = RandoRegion{ .regionName = "Kitchen", .mapId = MAP_3C_RBB_KITCHEN,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_1,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_2,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_3,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_4,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_5,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_6,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_7,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_8,			CAN_ATTACK),
			CHECK(RC_RBB_BLUE_EGG_KITCHEN_9,			CAN_ATTACK),
			CHECK(RC_RBB_MUMBO_TOKEN_INSIDE_KITCHEN,	true),
			CHECK(RC_RBB_NOTE_KITCHEN_1,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_2,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_3,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_4,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_5,				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_NAVIGATION_ROOM] = RandoRegion{ .regionName = "Navigation Room", .mapId = MAP_3D_RBB_NAVIGATION_ROOM,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_NAVIGATION_ROOM_1,			CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_NAVIGATION_ROOM_2,			CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_NAVIGATION_ROOM_3,			CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_NAVIGATION_ROOM_4,			CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_INSIDE_NAVIGATION_ROOM,	true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_1, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_2, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_3, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_4, 				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_FIRST] = RandoRegion{ .regionName = "Shipping Container First", .mapId = MAP_37_RBB_CONTAINER_1,
        .checks = {
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_FIRST_SHIPPING_CONTAINER_1,			CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_FIRST_SHIPPING_CONTAINER_2,			CAN_ATTACK),
			CHECK(RC_RBB_HONEYCOMB_BEEHIVE_FIRST_SHIPPING_CONTAINER_3,			CAN_ATTACK),
			CHECK(RC_RBB_MUMBO_TOKEN_UNDER_CHOMPA_INSIDE_FIRST_BLUE_CONTAINER, 	true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_1,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_2,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_3,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_4,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_5,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_6,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_7,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_8,				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_SECOND] = RandoRegion{ .regionName = "Shipping Container Second", .mapId = MAP_3E_RBB_CONTAINER_2,
        .checks = {
			CHECK(RC_RBB_JINJO_BLUE, 											true),
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BOX_INSIDE_SECOND_BLUE_CONTAINER,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP))),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_THIRD] = RandoRegion{ .regionName = "Shipping Container Third", .mapId = MAP_38_RBB_CONTAINER_3,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_1,	true),
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_2,	true),
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_3,	true),
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_4,	true),
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_5,	true),
			CHECK(RC_RBB_BLUE_EGG_SHIPPING_CONTAINER_INTERIOR_THIRD_6,	true),
			CHECK(RC_RBB_EXTRA_LIFE_BOOM_BOXES,							CAN_ATTACK),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_1,		true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_2,		true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_3,		true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_4,		true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_TNT_ROOM] = RandoRegion{ .regionName = "TNT Room", .mapId = MAP_3B_RBB_STORAGE_ROOM,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_TNT_ROOM_1,						CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_TNT_ROOM_2,						CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_TNT_ROOM_3,						CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_TNT_ROOM_4,						CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_BLUE_EGG_TNT_ROOM_5,						CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BOX_INSIDE_TNT_ROOM,	true),
			CHECK(RC_RBB_NOTE_TNT_ROOM_1, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_2, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_3, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_4, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_5, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_LOWER] = RandoRegion{ .regionName = "Warehouse Lower", .mapId = MAP_35_RBB_WAREHOUSE,
        .checks = {
			CHECK(RC_RBB_BLUE_EGG_WAREHOUSE_INTERIOR_1, CAN_EXTEND_JUMP_DISTANCE || (CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
			CHECK(RC_RBB_BLUE_EGG_WAREHOUSE_INTERIOR_2, CAN_EXTEND_JUMP_DISTANCE || (CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
			CHECK(RC_RBB_BLUE_EGG_WAREHOUSE_INTERIOR_3, CAN_EXTEND_JUMP_DISTANCE || (CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
			CHECK(RC_RBB_BLUE_EGG_WAREHOUSE_INTERIOR_4, CAN_EXTEND_JUMP_DISTANCE || (CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
			CHECK(RC_RBB_BLUE_EGG_WAREHOUSE_INTERIOR_5, CAN_EXTEND_JUMP_DISTANCE || (CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP))),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_1,		CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_2,		CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_3,		CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_4,		CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_UPPER] = RandoRegion{ .regionName = "Warehouse Upper", .mapId = MAP_35_RBB_WAREHOUSE,
        .checks = {
			CHECK(RC_RBB_EXTRA_LIFE_WAREHOUSE,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_JIGGY_WAREHOUSE,		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_ENTRANCE, true),
		}
	};

}, {});
// clang-format on