#include "SaveEditorTooltips.h"

#include <cstdint>
#include <unordered_map>

#include "enums.h"
#include "port/Rando/Types.h"

static const std::unordered_map<int32_t, const char*> jiggyTooltips = {
    { JIGGY_01_MM_JINJO, "Rescue all the Jinjos" },
    { JIGGY_02_MM_TICKERS_TOWER, "Atop Ticker's tower" },
    { JIGGY_03_MM_MUMBOS_SKULL, "In the Shaman's Eye" },
    { JIGGY_4_MM_JUJU, "Feed Juju" },
    { JIGGY_5_MM_HUTS, "Smash the huts" },
    { JIGGY_06_MM_RUINS, "Explore the ruins" },
    { JIGGY_07_MM_HILL, "On a hill" },
    { JIGGY_8_MM_ORANGE_PADS, "Hit all of Conga's orange tiles" },
    { JIGGY_9_MM_CHIMPY, "Give an orange to Chimpy" },
    { JIGGY_A_MM_CONGA, "Defeat Conga" },
    { JIGGY_0B_TTC_JINJO, "Rescue all the Jinjos" },
    { JIGGY_0C_TTC_LIGHTHOUSE, "Atop the lighthouse" },
    { JIGGY_0D_TTC_ALCOVE_1, "In a high alcove" },
    { JIGGY_0E_TTC_ALCOVE_2, "In a seaside alcove" },
    { JIGGY_0F_TTC_POOL, "At the bottom of the pool" },
    { JIGGY_10_TTC_SANDCASTLE, "Solve the sandcastle puzzle" },
    { JIGGY_11_TTC_RED_X, "X marks the spot" },
    { JIGGY_12_TTC_NIPPER, "Defeat Nipper" },
    { JIGGY_13_TTC_LOCKUP, "Inside a Lockup" },
    { JIGGY_14_TTC_BLUBBER, "Find Blubber's bullions" },
    { JIGGY_15_CC_JINJO, "Rescue all the Jinjos" },
    { JIGGY_16_CC_SNIPPETS, "Defeat the mutant snippets" },
    { JIGGY_17_CC_CLANKER_RAISED, "Give Clanker some fresh air" },
    { JIGGY_18_CC_BOLT, "In an alcove above Clanker's head" },
    { JIGGY_19_CC_TAIL, "In an alcove above Clanker's tail" },
    { JIGGY_1A_CC_LONG_PIPE, "In an underwater pipe" },
    { JIGGY_1B_CC_TOOTH, "Cure Clanker's toothache" },
    { JIGGY_1C_CC_RINGS, "Solve the ring challenge" },
    { JIGGY_1D_CC_SLOW_SAWBLADES, "At the end of slow sawblades" },
    { JIGGY_1E_CC_FAST_SAWBLADES, "At the end of fast sawblades" },
    { JIGGY_1F_BGS_JINGO, "Rescue all the Jinjos" },
    { JIGGY_20_BGS_ELEVATED_WALKWAY, "Solve the walkway challenge" },
    { JIGGY_21_BGS_PINKEGG, "Hatch the pink egg" },
    { JIGGY_22_CROCTUS, "Feed Croctus" },
    { JIGGY_23_BGS_HUTS, "Smash the huts" },
    { JIGGY_24_BGS_FLIBBITS, "Defeat the yellow Flibbits" },
    { JIGGY_25_BGS_MAZE, "Solve the maze challenge" },
    { JIGGY_26_BGS_TANKTUP, "Cure Tanktup's aching feet" },
    { JIGGY_27_BGS_TIPTUP, "Solve Titup's choir challenge" },
    { JIGGY_28_BGS_MR_VILE, "Beat Mr. Vile's challenges" },
    { JIGGY_29_FP_JINJO, "Rescue the Jinjos" },
    { JIGGY_2A_FP_BOGGY_1, "Pounce Boggy with a sled" },
    { JIGGY_2B_FP_PIPE, "In the snowman's pipe" },
    { JIGGY_2C_FP_BOGGY_3, "Race Boggy as Banjo" },
    { JIGGY_2D_FP_SNOWMAN_BUTTONS, "Bomb the snowman's buttons" },
    { JIGGY_2E_FP_PRESENTS, "Give the cubs their presents" },
    { JIGGY_2F_FP_XMAS_TREE, "Light up the Christmas Tree" },
    { JIGGY_30_FP_BOGGY_2, "Race Boggy as a Walrus" },
    { JIGGY_31_FP_SIR_SLUSH, "Bomb all the Sir Slush enemies" },
    { JIGGY_32_FP_WOZZA, "Greet Wozza as a Walrus" },
    { JIGGY_33_LAIR_1ST_JIGGY, "The first jiggy" },
    { JIGGY_34_LAIR_MM_WITCH_SWITCH, "Atop the entrance to Mumbo's Mountain" },
    { JIGGY_35_LAIR_CC_WITCH_SWITCH, "Peg the witch's eyes" },
    { JIGGY_36_LAIR_TTC_WITCH_SWITCH, "Shot out of a cannon near TTC" },
    { JIGGY_37_LAIR_BGS_WITCH_SWITCH, "Smash the witch's hat" },
    { JIGGY_38_LAIR_FP_WITCH_SWITCH, "In the advent calendar" },
    { JIGGY_39_LAIR_MMM_WITCH_SWITCH, "In the witch's eye" },
    { JIGGY_3A_LAIR_GV_WITCH_SWITCH, "In the sarcophagus" },
    { JIGGY_3B_LAIR_RBB_WITCH_SWITCH, "On a high platform" },
    { JIGGY_3C_LAIR_CCW_WITCH_SWITCH, "Buzz to the highest tree nook" },
    { JIGGY_3D_GV_JINJO, "Rescue the Jinjos" },
    { JIGGY_3E_GV_GRABBA, "Steal from Grabba" },
    { JIGGY_3F_GV_SHYINX, "Inside Jinxy" },
    { JIGGY_40_GV_MATCHING_GAME, "Solve the matching game" },
    { JIGGY_41_GV_MAZE, "Solve Sandybutt's maze" },
    { JIGGY_42_GV_WATER_PYRAMID, "Inside the water pyramid" },
    { JIGGY_43_GV_HISTUP, "High in Rubee's pyramid" },
    { JIGGY_44_GV_GOBI_1, "Free Gobi" },
    { JIGGY_45_GV_GOBI_2, "Give Trunker some water" },
    { JIGGY_46_GV_ANCIENT_ONES, "Solve the Ancient Ones challenge" },
    { JIGGY_47_CCW_JINJO, "Rescue the Jinjos" },
    { JIGGY_48_CCW_HOUSE, "Inside the completed house" },
    { JIGGY_49_CCW_EYRIE, "Guide Eyrie to adulthood" },
    { JIGGY_4A_CCW_NABNUT, "Give Nabnut his acorns" },
    { JIGGY_4B_CCW_GNAWTY, "Smash the boulder for Gnawty" },
    { JIGGY_4C_CCW_ZUBBAS, "Defeat the Zubbas" },
    { JIGGY_4D_CCW_FLOWER, "Guide the flower to maturity" },
    { JIGGY_4E_CCW_SUMMER_LEAF_JUMPS, "On a summer leaf" },
    { JIGGY_4F_CCW_TREE_TOP, "At the top of the giant tree" },
    { JIGGY_50_CCW_TOP_ROOM, "Inside the giant tree" },
    { JIGGY_51_RBB_JINJO, "Rescue the Jinjos" },
    { JIGGY_52_RBB_WAREHOUSE, "In the warehouse" },
    { JIGGY_53_RBB_SNORKEL, "Free Snorkel" },
    { JIGGY_54_RBB_WHISTLE, "Solve the whistle puzzle" },
    { JIGGY_55_RBB_FUNNEL, "Atop a smoke stack" },
    { JIGGY_56_RBB_BOSS_BOOM_BOX, "Defeat Boss Boom Box" },
    { JIGGY_57_RBB_PROPELLOR, "Behind the ship's rear propellors" },
    { JIGGY_58_RBB_CAPTAINS_CABIN, "In the captain's cabin" },
    { JIGGY_59_RBB_CRANE_CAGE, "In the cage" },
    { JIGGY_5A_RBB_ENGINE_ROOM, "In the engine room" },
    { JIGGY_5B_MMM_JINJO, "Rescue the Jinjos" },
    { JIGGY_5C_MMM_WELL, "At the bottom of the well" },
    { JIGGY_5D_MMM_NAPPER, "Sneak through Napper" },
    { JIGGY_5E_MMM_CELLAR, "In the cellar" },
    { JIGGY_5F_MMM_CHURCH_ROOF, "At the top of the church" },
    { JIGGY_60_MMM_MOTZHAND, "Solve Motzand's challenge" },
    { JIGGY_61_MMM_RAIN_BARREL, "In the drainpipe" },
    { JIGGY_62_MMM_TUMBLAR, "Solve Tumblar's challenge" },
    { JIGGY_63_MMM_FLOWER_POTS, "Give eggs to the flowerpots" },
    { JIGGY_64_MMM_LOGGO, "Inside Loggo" },
};

static const std::unordered_map<int32_t, const char*> honeycombTooltips = {
    { HONEYCOMB_1_MM_HILL, "In a nook on the mountainside" },
    { HONEYCOMB_2_MM_JUJU, "Above Juju" },
    { HONEYCOMB_3_TTC_UNDERWATER, "Under the sea" },
    { HONEYCOMB_4_TTC_FLOATING_BOX, "On flotsam in the ocean" },
    { HONEYCOMB_5_CC_UNDERWATER, "Inside a pipe underwater" },
    { HONEYCOMB_6_CC_ABOVE_WATER, "Inside a pipe above water" },
    { HONEYCOMB_7_BGS_MUMBOS, "In Mumbo's skull" },
    { HONEYCOMB_8_BGS_TANKTUP, "Above Tiptup's podium" },
    { HONEYCOMB_9_FP_WOZZAS_CAVE, "In Wozza's cave" },
    { HONEYCOMB_A_FP_SIR_SLUSH, "Under a Sir Slush" },
    { HONEYCOMB_B_GV_CACTUS, "Fly through a cactus" },
    { HONEYCOMB_C_GV_GOBI_3, "Make Gobi cough it up" },
    { HONEYCOMB_D_CCW_GNAWTYS, "In Gnawty's house" },
    { HONEYCOMB_E_CCW_NABNUTS, "In Nabnut's attic" },
    { HONEYCOMB_F_RBB_BOAT_HOUSE, "In the boathouse" },
    { HONEYCOMB_10_RBB_ENGINE_ROOM, "In the engine room" },
    { HONEYCOMB_11_MMM_CHURCH_RAFTERS, "In the church rafters" },
    { HONEYCOMB_12_MMM_FLOORBOARD, "Under the floorboards" },
    { HONEYCOMB_13_SM_STUMP, "On a stump" },
    { HONEYCOMB_14_SM_WATERFALL, "Behind the waterfall" },
    { HONEYCOMB_15_SM_UNDERWATER, "In an underwater alcove" },
    { HONEYCOMB_16_SM_TREE, "Above a tree" },
    { HONEYCOMB_17_SM_COLLIWOBBLE, "Peck Colliwobble" },
    { HONEYCOMB_18_SM_QUARRIES, "Barge the Quarries" },
};

static const std::unordered_map<int32_t, const char*> mumboTokenTooltips = {
    { MUMBOTOKEN_01_MM_STUMP_NEAR_CONGA, "On a stump near Conga" },
    { MUMBOTOKEN_02_MM_BEHIND_RUINS, "Behind the ruins" },
    { MUMBOTOKEN_03_MM_UNDER_RAMP_TO_MUMBOS_SKULL, "Under the ramp to the shaman's skull" },
    { MUMBOTOKEN_04_MM_BEHIND_PINK_JINJO, "Behind the Pink Jinjo" },
    { MUMBOTOKEN_05_MM_INSIDE_TICKERS_TOWER, "Inside Ticker's tower" },
    { MUMBOTOKEN_06_TTC_INSIDE_SALTY_HIPPO, "Inside the Salty Hippo" },
    { MUMBOTOKEN_07_TTC_INSIDE_LOCKUP_1, "Inside a Lockup" },
    { MUMBOTOKEN_08_TTC_INSIDE_LOCKUP_2, "Also inside a Lockup" },
    { MUMBOTOKEN_09_TTC_SALTY_HIPPO_MAST, "Under the crow's nest" },
    { MUMBOTOKEN_0A_TTC_BEHIND_LIGHTHOUSE_DOOR, "Behind the lighthouse's door" },
    { MUMBOTOKEN_0B_TTC_ON_FLOATING_BOX, "On flotsam in the bay" },
    { MUMBOTOKEN_0C_TTC_BEHIND_PILLAR_UNDERWATER, "Behind a pillar in the water" },
    { MUMBOTOKEN_0D_TTC_POND_BOTTOM, "At the bottom of a pond" },
    { MUMBOTOKEN_0E_TTC_FLOATING_ABOVE_SHOCKJUMP_PAD, "Above the shock jump pad" },
    { MUMBOTOKEN_0F_TTC_BEHIND_NIPPER, "Behind Nipper" },
    { MUMBOTOKEN_10_CC_CHOMPA_BEHIND_CLANKERS_TAIL, "On a pipe near Clanker's tail" },
    { MUMBOTOKEN_11_CC_ABOVE_LEVEL_ENTRANCE, "Above the entrance pipe" },
    { MUMBOTOKEN_12_CC_TUNNEL_RIGHT_OF_CLANKER, "In an underwater tunnel" },
    { MUMBOTOKEN_13_CC_ALCOVE_WITH_OPEN_GRATE, "In a high alcove" },
    { MUMBOTOKEN_14_CC_CLANKERS_LEFT_TOOTH, "Cure Clanker's toothache" },
    { MUMBOTOKEN_15_BGS_UNDER_HUT_1, "In the swamp near the huts" },
    { MUMBOTOKEN_16_BGS_UNDER_HUT_2, "Also in the swamp near the huts" },
    { MUMBOTOKEN_17_BGS_TOP_OF_POLE_NEXT_TO_BIG_EGG, "On a cattail near the pink egg" },
    { MUMBOTOKEN_18_BGS_BEHIND_YELLOW_JINJO, "Behind the Yellow Jinjo" },
    { MUMBOTOKEN_19_BGS_FLOATING_BETWEEN_HUT_AND_CROCTUS, "In the air near the huts" },
    { MUMBOTOKEN_1A_BGS_BEHIND_MUMBOS_SKULL, "Behind the shaman's skull" },
    { MUMBOTOKEN_1B_BGS_ALCOVE_ABOVE_YELLOW_FLIBBITS, "In an alcove above the first jiggy switch" },
    { MUMBOTOKEN_1C_BGS_BEHIND_TIPTUP, "Behind Tiptup" },
    { MUMBOTOKEN_1D_BGS_INSIDE_MR_VILES, "Inside the big crocodile" },
    { MUMBOTOKEN_1E_BGS_INSIDE_MUMBOS_SKULL, "Behind Mumbo's chair" },
    { MUMBOTOKEN_1F_FP_SNOWMAN_LEFT_FOOT, "Near the big snowman's left foot" },
    { MUMBOTOKEN_20_FP_SNOWMAN_RIGHT_FOOT, "Near the big snowman's right foot" },
    { MUMBOTOKEN_21_FP_BEHIND_PILE_PRESENT_BOXES, "Behind the pile of presents" },
    { MUMBOTOKEN_22_FP_ABOVE_CHIMNEY_FLIGHT_PAD, "Above the chimney flight pad" },
    { MUMBOTOKEN_23_FP_INSIDE_SIR_SLUSH_NEAR_SNOWMANS_LEFT_FOOT, "Under a Sir Slush" },
    { MUMBOTOKEN_24_FP_INSIDE_SIR_SLUSH_NEAR_SNOWMANS_RIGHT_FOOT, "Under another Sir Slush" },
    { MUMBOTOKEN_25_FP_CHRISTMAS_TREE_POT, "Inside the Christmas Tree's pot" },
    { MUMBOTOKEN_26_FP_TIP_OF_SCARF, "At the tip of the big snowman's scarf" },
    { MUMBOTOKEN_27_FP_WATER_BEHIND_SNOWMAN, "In the water behind the big snowman" },
    { MUMBOTOKEN_28_FP_INSIDE_BOGGYS_IGLOO, "Inside Boggy's igloo" },
    { MUMBOTOKEN_29_GV_TOP_OF_JINXYS_NOSE, "On Jinxy's nose" },
    { MUMBOTOKEN_2A_GV_SAND_RIGHT_OF_JINXY, "In the sand near Jinxy" },
    { MUMBOTOKEN_2B_GV_BOTTOM_OF_MOAT, "At the bottom of the moat" },
    { MUMBOTOKEN_2C_GV_TOP_OF_WATER_PYRAMID, "Atop the water pyramid" },
    { MUMBOTOKEN_2D_GV_FRONT_OF_STAR_DOOR, "In front of the water pyramid" },
    { MUMBOTOKEN_2E_GV_INSIDE_MEMORY_GAME_ROOM, "Inside the matching pyramid" },
    { MUMBOTOKEN_2F_GV_BEHIND_SANDYBUTTS_SARCOPHAGUS, "Behind Sandybutt's sarcophagus" },
    { MUMBOTOKEN_30_GV_INSIDE_WATER_PYRAMID, "Inside the water pyramid" },
    { MUMBOTOKEN_31_GV_NEXT_TO_RUBEE, "Near Rubee" },
    { MUMBOTOKEN_32_GV_INSIDE_JINXY, "Inside Jinxy" },
    { MUMBOTOKEN_33_MMM_HIDDEN_NEAR_FOUNTAIN, "Near the fountain" },
    { MUMBOTOKEN_34_MMM_NEAR_FRONT_TUMBLARS_SHED, "Near Tumblar's shed" },
    { MUMBOTOKEN_35_MMM_ALCOVE_CLOCK_TOWER, "In an alcove near the clock tower" },
    { MUMBOTOKEN_36_MMM_NEXT_TO_MAZE_HEDGE_RAMP, "Near the hedge maze" },
    { MUMBOTOKEN_37_MMM_IN_THE_MAZE, "In the hedge maze" },
    { MUMBOTOKEN_38_MMM_BEHIND_CHURCH, "Behind the church" },
    { MUMBOTOKEN_39_MMM_INSIDE_WHIPCRACK_IN_FOUNTAIN, "Inside the fountain" },
    { MUMBOTOKEN_3A_MMM_TOP_OF_RAFTER_INSIDE_CHURCH, "Among the church rafters" },
    { MUMBOTOKEN_3B_MMM_TOP_OF_STOOL_INSIDE_CHURCH, "On the stool in the church" },
    { MUMBOTOKEN_3C_MMM_TOP_OF_TUMBLARS_SHED, "On the roof of the shed" },
    { MUMBOTOKEN_3D_MMM_INSIDE_LOGGO_AND_INSIDE_BARREL_IN_CELLAR, "In the cellar" },
    { MUMBOTOKEN_3E_MMM_IN_CHIMNEY_INSIDE_DINNING_ROOM, "In the mansion's chimney" },
    { MUMBOTOKEN_3F_MMM_INSIDE_WELL, "Inside the well" },
    { MUMBOTOKEN_40_MMM_INSIDE_BEDROOM, "In the mansion's bedroom" },
    { MUMBOTOKEN_41_MMM_SINK_IN_LOGGOS_ROOM, "In the mansion's bathroom" },
    { MUMBOTOKEN_42_RBB_TOP_OF_SHIPS_CHIMNEY, "On the ship's smokestack" },
    { MUMBOTOKEN_43_RBB_SHIPS_PROW, "On the ship's prow" },
    { MUMBOTOKEN_44_RBB_ON_LIFE_BOAT, "On the lifeboat" },
    { MUMBOTOKEN_45_RBB_FRONT_OF_CHOMPA_LEFT_OF_SHIP, "On a toll walkway" },
    { MUMBOTOKEN_46_RBB_TOXIC_WASTE_POND, "Near the toxic waste" },
    { MUMBOTOKEN_47_RBB_UNDER_CHOMPA_IN_WITCH_SWITCH_TOWER, "Near the witch switch" },
    { MUMBOTOKEN_48_RBB_UNDER_CHOMPA_INSIDE_FIRST_BLUE_CONTAINER, "Inside the first blue container" },
    { MUMBOTOKEN_49_RBB_TOP_OF_BOX_INSIDE_SECOND_BLUE_CONTAINER, "Inside the second blue container" },
    { MUMBOTOKEN_4A_RBB_TOP_OF_BUNK_IN_CABIN, "On a bed in the cabin" },
    { MUMBOTOKEN_4B_RBB_INSIDE_NAVIGATION_ROOM, "In the navigation room" },
    { MUMBOTOKEN_4C_RBB_INSIDE_KITCHEN, "In the kitchen" },
    { MUMBOTOKEN_4D_RBB_ENGINE_ROOM_LEFT_PIPE, "In the engine room above the left pipe" },
    { MUMBOTOKEN_4E_RBB_ENGINE_ROOM_RIGHT_PIPE, "In the engine room above the right pipe" },
    { MUMBOTOKEN_4F_RBB_ENGINE_ROOM_SPINNING_PLATFORM, "In the engine room on a spinning crank" },
    { MUMBOTOKEN_50_RBB_TOP_OF_BOX_INSIDE_TNT_ROOM, "In the third blue container" },
    { MUMBOTOKEN_51_LAIR_BEHIND_PURPLE_CAULDRON, "Behind the first purple cauldron" },
    { MUMBOTOKEN_52_LAIR_CCW_JIGGY_PODIUM, "Near the CCW jiggy puzzle" },
    { MUMBOTOKEN_53_LAIR_TOP_OF_PIPE_IN_ORANGE_CAULDRON_ROOM, "On the pipe in the orange cauldron room" },
    { MUMBOTOKEN_54_LAIR_ABOVE_CC_ENTRANCE, "Above the CC entrance" },
    { MUMBOTOKEN_55_LAIR_BEHIND_SARCOPHAGUS, "Behind the sarcophagus" },
    { MUMBOTOKEN_56_LAIR_ADVENT_TOP_WINDOW, "In the advent calendar" },
    { MUMBOTOKEN_57_LAIR_BEHIND_MUMBO_IN_CRYPT, "Behind the shaman's chair" },
    { MUMBOTOKEN_58_LAIR_ABOVE_NOTE_DOOR_WATER_AREA, "Above a note door" },
    { MUMBOTOKEN_59_LAIR_UNDERWATER_RBB_ENTRANCE_AREA, "Underwater near RBB" },
    { MUMBOTOKEN_5A_LAIR_WHIPCRACK_NEAR_MMM_JIGGY_PODIUM, "In an alcove near the MMM puzzle" },
    { MUMBOTOKEN_5B_CCW_SPRING_UNFINISHED_WOOD_TREEHOUSE, "Near the unfinished treehouse" },
    { MUMBOTOKEN_5C_CCW_SPRING_TOP_OF_BRANCH, "On a tree branch" },
    { MUMBOTOKEN_5D_CCW_SPRING_FRONT_OF_EYRIE, "Near Eyrie" },
    { MUMBOTOKEN_5E_CCW_SPRING_THORN_FIELD_FRONT_OF_MUMBOS_SKULL, "In the thorny field" },
    { MUMBOTOKEN_5F_CCW_SPRING_SNAREBEAR_NEAR_BIG_FLOWER, "In a snarebear near the flower" },
    { MUMBOTOKEN_60_CCW_SPRING_SNAREBEAR_NEAR_ENTRANCE, "In a snarebear near the entrance" },
    { MUMBOTOKEN_61_CCW_SPRING_TOP_OF_BEEHIVE, "In the Zubba's nest" },
    { MUMBOTOKEN_62_CCW_SPRING_NABNUTS_HOUSE, "In Nabnut's house" },
    { MUMBOTOKEN_63_CCW_SUMMER_PLATFORMS_BEFORE_EYRIES_NEST, "" },
    { MUMBOTOKEN_64_CCW_SUMMER_BIG_FLOWER_FIELD, "In the flower field" },
    { MUMBOTOKEN_65_CCW_SUMMER_SNAREBEAR_NEAR_THORN_FIELD, "In a snarebear near the thorn field" },
    { MUMBOTOKEN_66_CCW_SUMMER_TOP_OF_BRANCH, "On a tree branch" },
    { MUMBOTOKEN_67_CCW_SUMMER_ENTRANCE_GNAWTYS_HOUSE, "Near the entrance to Gnawty's house" },
    { MUMBOTOKEN_68_CCW_SUMMER_FLOATING_ABOVE_BIG_CLUCKER, "Above a Big Clucker" },
    { MUMBOTOKEN_69_CCW_SUMMER_INSIDE_MUMBOS_SKULL, "Inside the shaman's skull" },
    { MUMBOTOKEN_6A_CCW_AUTUMN_FLOATING_ABOVE_BIG_CLUCKER, "Above a Big Clucker" },
    { MUMBOTOKEN_6B_CCW_AUTUMN_SNAREBEAR_NEAR_ENTRANCE, "In a snarebear near the entrance" },
    { MUMBOTOKEN_6C_CCW_AUTUMN_SNAREBEAR_TOP_OF_TREE, "In a snarebear at the top of the tree" },
    { MUMBOTOKEN_6D_CCW_AUTUMN_LEAF_NEAR_TREEHOUSE, "On a leaf near the treehouse" },
    { MUMBOTOKEN_6E_CCW_AUTUMN_TOP_OF_BRANCH, "On a tree branch" },
    { MUMBOTOKEN_6F_CCW_WINTER_BIG_FLOWER, "Near the wilted flower" },
    { MUMBOTOKEN_70_CCW_WINTER_FROZEN_RIVER_NEAR_FLIGHT_PAD, "On the ice near the flight pad" },
    { MUMBOTOKEN_71_CCW_WINTER_BROKEN_BEEHIVE, "In the broken Zubba's nest" },
    { MUMBOTOKEN_72_CCW_WINTER_WALKWAY_FRONT_OF_NABNUTS_HOUSE, "On the walkway in front of Nabnut's house" },
    { MUMBOTOKEN_73_CCW_WINTER_SIR_SLUSH_BETWEEN_BIG_FLOWER_AND_MUMBOS_SKULL, "Under a Sir Slush" },
    { RP_MUMBO_TOKEN_INSIDE_LOGGO, "Inside Loggo" }, // only reachable with the MMM duplicate-id fix enabled
};

static const char* LookupTooltip(const std::unordered_map<int32_t, const char*>& tooltips, int32_t id) {
    auto entry = tooltips.find(id);
    return entry != tooltips.end() ? entry->second : "";
}

const char* SaveEditor_GetJiggyTooltip(jiggy_e jiggyId) {
    return LookupTooltip(jiggyTooltips, jiggyId);
}

const char* SaveEditor_GetHoneycombTooltip(honeycomb_e honeycombId) {
    return LookupTooltip(honeycombTooltips, honeycombId);
}

const char* SaveEditor_GetMumboTokenTooltip(mumbotoken_e tokenId) {
    return LookupTooltip(mumboTokenTooltips, tokenId);
}
