file(MAKE_DIRECTORY "${BUNDLE}/assets")
file(COPY "${SOURCE_DIR}/assets/yaml" DESTINATION "${BUNDLE}/assets")
file(COPY "${SOURCE_DIR}/config.yml" DESTINATION "${BUNDLE}")

foreach(file gamecontrollerdb.txt lighthouse.o2r)
    set(found "")
    foreach(dir "${BINARY_DIR}" "${SOURCE_DIR}")
        if(EXISTS "${dir}/${file}" AND NOT found)
            file(SIZE "${dir}/${file}" size)
            if(size GREATER 0)
                set(found "${dir}/${file}")
            endif()
        endif()
    endforeach()
    if(found)
        file(COPY "${found}" DESTINATION "${BUNDLE}")
    elseif(file STREQUAL "lighthouse.o2r")
        message(WARNING "iOS bundle: lighthouse.o2r is missing; build the GeneratePortO2R "
                        "target or the app will exit on launch")
    else()
        message(WARNING "iOS bundle: ${file} is missing; controller mappings may be incomplete")
    endif()
endforeach()

file(REMOVE "${BUNDLE}/bk.o2r")
file(REMOVE_RECURSE "${BUNDLE}/mods")
if(BUNDLE_ROM)
    if(NOT EXISTS "${BUNDLE_ROM}")
        message(FATAL_ERROR "LIGHTHOUSE_BUNDLE_ROM does not exist: ${BUNDLE_ROM}")
    endif()
    configure_file("${BUNDLE_ROM}" "${BUNDLE}/bk.o2r" COPYONLY)
endif()
if(BUNDLE_MODS)
    file(GLOB bundle_mods "${BUNDLE_MODS}/*.o2r" "${BUNDLE_MODS}/*.otr")
    if(NOT bundle_mods)
        message(FATAL_ERROR "LIGHTHOUSE_BUNDLE_MODS holds no .o2r or .otr: ${BUNDLE_MODS}")
    endif()
    file(COPY ${bundle_mods} DESTINATION "${BUNDLE}/mods")
endif()
